name: AWS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-54-242-236-21.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
